### ISSUE TITLE
Support for .net 8 targeting without platform

### ISSUE THREAD

**Issue by TheresasAccount** [FreakyAli/Maui.FreakyEffects#14]
Hi, I am trying to get this to work with my project and my unit test setup requires the unit test target to be a class library instead of a Maui app.

Is it possible to have this target just .Net8 without platform?

Thanks :)

**Comment by FreakyAli** [comment]
Hey @TheresasAccount, 

I am a bit occupied and don't have enough time for now (Especially for February), If I get time to do this I will try. 
In the meantime, If you could make the necessary changes and raise a PR I think I can review it and merge and create a Release!

**Comment by FreakyAli** [comment]
@TheresasAccount A new version is out take a look

**Comment by FreakyAli** [comment]
Also FYI, I will be throwing a NotImplementedException from these .net methods, in the next release I kinda forgot about it in this release, so make sure you update your tests when you update to the next version.
