### ISSUE TITLE
Maui namespace not found

### ISSUE THREAD

**Issue by davepruitt** [FreakyAli/Maui.FreakyEffects#3]
I've tried using your TouchEffect in my MAUI project, but when I attempt to use it I just get a compile time error:

"The type or namespace name 'Maui' could not be found".

I installed the pre-release package from Nuget. I am using .NET 7.

**Comment by FreakyAli** [comment]
I see, can you add a sample project that has this error? Also have you tried using the sample from here and checked if you get the same error?

**Comment by FreakyAli** [comment]
@davepruitt  Have you fixed this? if so let me know!

**Comment by FreakyAli** [comment]
Closing this since I did not get a response, if you do still face this issue I will be glad to help!
